@startuml
actor user as u

  usecase "StartGame" as UCA1
  usecase "RegisterPlayers" as UCA2



  usecase "TakeTurn" as UC1
  usecase "LandOnField" as UC2

  usecase "LandOnProperty" as UC4
  usecase "LandOnConsequence" as UC5
  usecase "MakeChoice" as UC6
  usecase "HandleMoney" as UC7
 usecase "QuitGame" as UC8

u --> (UCA1)
(UCA1) --> (UC1) : proceeds
(UCA1) --> (UCA2) : proceeds
(UCA2) --> (UC1) : proceeds

(UC1) --> (UC2) : invokes
(UC1) --> (UC8) : proceeds

(UC2) --> (UC4)
(UC2) --> (UC5)

(UC4) --> (UC6)
(UC5) --> (UC6)

(UC6) --> (UC1)
(UC6) --> (UC7)
(UC7) --> (UC1)


@enduml